___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np #sử dụng bộ thư viện numpy

In [3]:
arr = np.arange(0,11) #tạo ra mảng tăng dần từ 0 - 10

In [4]:
arr #hiển thị

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
arr[8] #lấy ra phần tử có index là 8

8

In [6]:
arr[1:5] #lấy ra phần tử có index từ 1 - 4

array([1, 2, 3, 4])

In [7]:
arr[0:5] #lấy ra phần tử có index từ 0 - 4

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
#truyền 100 vào phần tử 0 tới 4
arr[0:5]=100

#hiển thị
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#truyền một mảng tăng dần từ 1 - 10 vào phần tử 1 - 10 của mảng
arr = np.arange(0,11)

#hiển thị
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#trích xuất mảng từ phần tử 0 đến 5 gán vào một biến
slice_of_arr = arr[0:6]

#hiển thị mảng
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
#tất cả mảng được truyền vào 99 để thay thế
slice_of_arr[:]=99

#hiển thị
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [16]:
#sao chép ra một mảng mới
arr_copy = arr.copy()

arr_copy #in ra mảng mới có giá trị tương tự

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [17]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) #tạo mảng 2 chiều

#hiển thị
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
#in ra hàng có index 1
arr_2d[1]


array([20, 25, 30])

In [19]:
# có 2 kiểu dịnh dạng arr_2d[row][col] hoặc arr_2d[row,col] để gọi giá trị

# cách thứ nhất viết như gọi mảng truyền thống
arr_2d[1][0]

20

In [20]:
# cách thứ 2 truyền vào 1 cặp position vị trị của giá trị trong matrix
arr_2d[1,0]

20

In [21]:
# trích dẫn matrix

# trích dẫn một phần của matrix
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
#trích dẫn hàng thứ 2 của matrix
arr_2d[2]

array([35, 40, 45])

In [26]:
#lấy toàn bộ hàng 2 của matrix, tương tự như cách trên
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [29]:
#tạo một matrix giá trị 0, có độ lớn 10x10
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
#lấy ra độ lớn của mảng sau khi định dạng lại mảng, 1 là lấy chiều dài của mảng
arr_length = arr2d.shape[1]
arr_length

10

In [34]:
#tạo ra một matrix có giá trị mỗi hàng bằng index mỗi hàng

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [35]:
arr2d[[2,4,6,8]] #lấy ra hàng 2 4 6 8 của mảng

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [37]:
#thích lấy hàng nào cũng được, không cần theo thứ tự, có thể duplicate
arr2d[[6,4,2,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [38]:
arr = np.arange(1,11) #tạo mảng numpy trong khoảng 1 - 10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4 #so sánh logic tất cả phần tử trong mảng

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4 #sẽ tạo ra một mảng chứa các phần tử kết quả từng phần tử của matrix numpy

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr] #lấy ra những phần tử thỏa mãn điều kiện của mảng so sánh (có giá trị True)

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr>2] #lấy ra giá trị trong matrix numpy lớn hơn 2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
x = 2 #tạo một biến
arr[arr>x] #lấy ra các kết quả thỏa mãn điều kiện trong matrix numpy

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Gút chóp!
